config/routes.rb
# == Route Map
#

# frozen_string_literal: true

Rails.application.routes.draw do
  # Defines the root path route ("/")
  get '/' => 'dashboard#index', locale: :uk
  get '/:locale' => 'dashboard#index'

  scope '/:locale', locale: /#{I18n.available_locales.join("|")}/ do
    devise_scope :user do
      # Redirests signing out users back to sign-in
      get 'users', to: 'dashboard#index'
    end
    devise_for :accounts
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  end
end

app/models/account.rb
# frozen_string_literal: true

# :nodoc:
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :timeoutable, :trackable
end

# == Schema Information
#
# Table name: accounts
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  confirmation_token     :string
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string
#  failed_attempts        :integer          default("0"), not null
#  unlock_token           :string
#  locked_at              :datetime
#
# Indexes
#
#  index_accounts_on_confirmation_token    (confirmation_token) UNIQUE
#  index_accounts_on_email                 (email) UNIQUE
#  index_accounts_on_reset_password_token  (reset_password_token) UNIQUE
#  index_accounts_on_unlock_token          (unlock_token) UNIQUE
#

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# :nodoc:
class ApplicationController < ActionController::Base
  before_action :authenticate_account!
  around_action :with_locale

  def with_locale(&action)
    locale = params[:locale] || I18n.default_locale
    I18n.with_locale(locale, &action)
  end

  def default_url_options
    { locale: I18n.locale }
  end
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

# :nodoc:
class DashboardController < ApplicationController
  def index
    respond_to do |format|
      format.html
    end
  end
end

app/views/dashboard/index.html.erb
<div>
  <!-- app/views/dashboard/index.html.erb -->
  <%= link_to "Sign Out", destroy_account_session_path, data: { "turbo-method": :delete } %>
  <!-- END app/views/dashboard/index.html.erb -->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ITAid</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if notice || alert %>
      <%= render partial: 'components/messages/alert' %>
    <% end %>
    <%= yield %>
  </body>
</html>